### ISSUE TITLE
[Question/Suggestion] hCaptcha for API

### ISSUE THREAD

**Issue by seamive** [hCaptcha/react-native-hcaptcha#1]
Greetings,

We're planning to use hCaptcha for the react native apps. We wanted to confirm if the result response can be validated via API. So when user signups say using email and pass, it also sends the hCaptcha verification code with it on the server side so the requests can make sure it comes from the app itself. 

**Example:**
User input on mobile
```
**email:** human@captcha.com
**pass:** super pass
**solved captcha:** gets a response
```

**Send response to API endpoint**
`example.com/rest/v1/auth?email=human@captcha.com&pass=hashedPass&captcha=hcaptchaResponse`

If someone tries to manipulate or leave captcha param as invalid, it shouldn't process the DB?

Is this achievable?

Thanks!

**Comment by e271828-** [comment]
Hi, not sure I understand what you're asking. The response from the hCaptcha SDK should always be sent to your backend for validation. Please see: https://docs.hcaptcha.com/#basic-principles

**Comment by seamive** [comment]
I guess this is what we're looking for. To get a response on the client-side and verify it on the server-side.
https://docs.hcaptcha.com/#verify-the-user-response-server-side. Just one thing here is how can we validate based on devices?

**Comment by e271828-** [comment]
> I guess this is what we're looking for. To get a response on the client-side and verify it on the server-side.
> https://docs.hcaptcha.com/#verify-the-user-response-server-side. Just one thing here is how can we validate based on devices?

How do you mean?

**Comment by seamive** [comment]
Like this https://github.com/hCaptcha/react-native-hcaptcha/issues/1#issue-996400257

**Comment by e271828-** [comment]
@seamive still not sure I understand what you mean by "validate based on devices" but you can e.g. use different sitekeys on Android vs. iOS. This seems like a general q rather than related to the repo, so will close this issue.
