### ISSUE TITLE
bug-ish: 1.4.1 hasn't been published to npm

### ISSUE THREAD

**Issue by Rexogamer** [hCaptcha/react-native-hcaptcha#27]
According to the commit history and the repo's releases/tags, 1.4.1 is currently the latest version - however, 1.3.5 is the latest version that has been published to npm.

(No judgement here, by the way - forgetting to publish a version is perfectly understandable, especially as it's been pushed to the repo ^^)

**Comment by e271828-** [comment]
@Rexogamer 1.4.2 has now been published to NPM.
