### ISSUE TITLE
Automate npm publish on git tag

### ISSUE THREAD

**Issue by CAMOBAP** [hCaptcha/react-native-hcaptcha#38]
We can automate publication to npmjs.org (in a similar way to how we are done for ios-sdk). something similar to https://itnext.io/simplify-your-npm-publish-workflow-using-github-actions-691249bc7e59

@e271828-  feel free to close it if it's not necessary

**Comment by hirbod** [comment]
Is someone going to publish 1.5.1 to npm?

**Comment by CAMOBAP** [comment]
Merged
