### ISSUE TITLE
hcaptcha vulnerables

### ISSUE THREAD

**Issue by vyppN** [hCaptcha/react-native-hcaptcha#47]
There are some issues that cause by `babel-preset-react-native@4.0.1`

# Critical Severity
## Incomplete List of Disallowed Inputs

Vulnerable module: babel-traverse

### Workaround
Users who are unable to upgrade the library can upgrade the affected plugins instead, to avoid triggering the vulnerable code path in affected @babel/traverse.

### Remediation
There is no fixed version for `babel-traverse`.

# High Severity
## Regular Expression Denial of Service (ReDoS)

Vulnerable module: ansi-regex

### Remediation
Upgrade ansi-regex to version 3.0.1, 4.1.1, 5.0.1, 6.0.1 or higher.

**Comment by dprevost-LMI** [comment]
PR fixing the above: https://github.com/hCaptcha/react-native-hcaptcha/pull/51
