### ISSUE TITLE
onMessage function is executing multiple times

### ISSUE THREAD

**Issue by bind-furqan** [hCaptcha/react-native-hcaptcha#5]
I am using the HCaptcha react native library. It seems the onMessage function is executing multiple times and app is crashing with the error `Maximum call stack size exceeded`

`import ConfirmHcaptcha from "@hcaptcha/react-native-hcaptcha"`

using inside the render function.
`<ConfirmHcaptcha
        baseUrl={baseUrl}
        languageCode="en"
        onMessage={messageEvent}
        ref={captchaForm}
        siteKey={siteKey}
      />`

messageEvent function details

`const messageEvent = event => {
    if (event && event.nativeEvent.data) {
      if (['cancel', 'error', 'expired'].includes(event.nativeEvent.data)) {
        captchaForm.current.hide();
        return;
      } else {
        console.log('Verified code from hCaptcha', event.nativeEvent.data);
        setCode(event.nativeEvent.data)
        setTimeout(() => {
          captchaForm.current.hide();
          // do whatever you want here
        }, 1000)
      }
    }
  }`

I debugged the messageEvent function code, and it is executing the first time with a passcode, and then it is executing with the cancel text.

Please suggest if you know how I can stop the onMessage function multiple times execution to avoid the error?

**Comment by e271828-** [comment]
Hi, is this happening for you with the example app? Do you have a minimal repro?

**Comment by bind-furqan** [comment]
Thanks for the response. Yes, I am following the example app. 

I found the issue. It seems after getting the token in the onMessage callback, we are calling the `captchaForm.current.hide();` function to hide the HCaptcha view, but the library is calling onMessage callback again with the cancel text in the event data, and as per the example, calling `captchaForm.current.hide();` again inside the onMessage callback function for cancel condition, that keeps in a loop and calling onMessage callback multiple times until it crashes.

I skip calling `captchaForm.current.hide();` function for the cancel condition, so it only calls onMessage callback 2 times one for the success and another one for the cancel, but that is working fine, and the issue is resolved.

**Comment by e271828-** [comment]
Got it. Would you like to open a PR to clarify/document this behavior?

**Comment by bind-furqan** [comment]
[Open a PR](https://github.com/hCaptcha/react-native-hcaptcha/pull/6)
