### ISSUE TITLE
Expo build Issue: using node version 20 or higher

### ISSUE THREAD

**Issue by Ruchita-Missio** [hCaptcha/react-native-hcaptcha#69]
i am getting this below issue with using this package in expo. i am using latest version of node

Running "yarn install" in /Users/expo/workingdir/build directory
yarn install v1.22.21
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @rneui/themed@4.0.0-rc.8" has incorrect peer dependency "@rneui/base@4.0.0-rc.7".
warning "babel-preset-expo > @react-native/babel-preset > @react-native/babel-plugin-codegen > @react-native/codegen@0.74.85" has unmet peer dependency "@babel/preset-env@^7.1.6".
warning "babel-preset-expo > @react-native/babel-preset > @react-native/babel-plugin-codegen > @react-native/codegen > jscodeshift@0.14.0" has unmet peer dependency "@babel/preset-env@^7.1.6".
warning "react-native > @react-native/codegen@0.74.87" has unmet peer dependency "@babel/preset-env@^7.1.6".
warning "expo-splash-screen > @expo/prebuild-config@7.0.6" has unmet peer dependency "expo-modules-autolinking@>=0.8.1".
warning " > react-native-crisp-chat-sdk@0.14.4" has incorrect peer dependency "react-native@^0.73.6".
warning " > react-native-crisp-chat-sdk@0.14.4" has unmet peer dependency "react-dom@^18.2.0".
warning " > react-native-otp-inputs@7.4.0" has unmet peer dependency "@react-native-clipboard/clipboard@*".
warning "react-native-render-html > @native-html/transient-render-engine@11.2.3" has unmet peer dependency "@types/react-native@*".
warning "react-native-render-html > @native-html/transient-render-engine > @native-html/css-processor@1.11.0" has unmet peer dependency "@types/react@*".
warning "react-native-render-html > @native-html/transient-render-engine > @native-html/css-processor@1.11.0" has unmet peer dependency "@types/react-native@*".
warning " > redux-persist@6.0.0" has unmet peer dependency "redux@>4.0.0".
<--- Last few GCs --->
[1188:0x128040000]    63486 ms: Scavenge 2012.3 (2059.8) -> 2009.9 (2059.8) MB, 6.8 / 0.0 ms  (average mu = 0.396, current mu = 0.416) allocation failure; 
[1188:0x128040000]    63526 ms: Scavenge 2013.8 (2059.8) -> 2011.8 (2063.0) MB, 33.2 / 0.0 ms  (average mu = 0.396, current mu = 0.416) allocation failure; 
[1188:0x128040000]    63551 ms: Scavenge 2017.2 (2063.0) -> 2014.9 (2080.5) MB, 10.2 / 0.0 ms  (average mu = 0.396, current mu = 0.416) allocation failure; 
<--- JS stacktrace --->
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
1: 0x100b87c40 node::Abort() [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
 2: 0x100b87e24 node::ModifyCodeGenerationFromStrings(v8::Local<v8::Context>, v8::Local<v8::Value>, bool) [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
3: 0x100cdf27c v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
4: 0x100e89b60 v8::internal::EmbedderStackStateScope::EmbedderStackStateScope(v8::internal::Heap*, v8::internal::EmbedderStackStateScope::Origin, cppgc::EmbedderStackState) [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
5: 0x100e8d74c v8::internal::Heap::CollectSharedGarbage(v8::internal::GarbageCollectionReason) [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
6: 0x100e8a760 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::internal::GarbageCollectionReason, char const*, v8::GCCallbackFlags) [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
7: 0x100e87a60 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
 8: 0x100e86b88 v8::internal::Heap::HandleGCRequest() [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
9: 0x100e34130 v8::internal::StackGuard::HandleInterrupts() [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
10: 0x101202d90 v8::internal::Runtime_StackGuard(int, unsigned long*, v8::internal::Isolate*) [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
11: 0x10155104c Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
12: 0x101568ea4 Builtins_ArrayPrototypeJoin [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
13: 0x1067e0040 
14: 0x1067dbcf0 
15: 0x1064b4254
16: 0x1014dc198 Builtins_InterpreterEntryTrampoline [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
17: 0x1014dc198 Builtins_InterpreterEntryTrampoline [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
18: 0x1015100d0 Builtins_GeneratorPrototypeNext [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
19: 0x106aabd44 
20: 0x106a6f1d8 
21: 0x1014dc198 Builtins_InterpreterEntryTrampoline [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
22: 0x1014dc198 Builtins_InterpreterEntryTrampoline [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
23: 0x1015100d0 Builtins_GeneratorPrototypeNext [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
24: 0x106aabd44 
25: 0x106a6f1d8 
26: 0x1014dc198 Builtins_InterpreterEntryTrampoline [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
27: 0x1014dc198 Builtins_InterpreterEntryTrampoline [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
28: 0x1015100d0 Builtins_GeneratorPrototypeNext [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
29: 0x1067cec68 
30: 0x106526074
31: 0x10159c738 Builtins_PromiseFulfillReactionJob [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
32: 0x1014ffc4c Builtins_RunMicrotasks [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
33: 0x1014da3a4 Builtins_JSRunMicrotasksEntry [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
34: 0x100e0b9ac v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
35: 0x100e0be9c v8::internal::(anonymous namespace)::InvokeWithTryCatch(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
36: 0x100e0c078 v8::internal::Execution::TryRunMicrotasks(v8::internal::Isolate*, v8::internal::MicrotaskQueue*, v8::internal::MaybeHandle<v8::internal::Object>*) [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
37: 0x100e327e0 v8::internal::MicrotaskQueue::RunMicrotasks(v8::internal::Isolate*) [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
38: 0x100e32f7c v8::internal::MicrotaskQueue::PerformCheckpoint(v8::Isolate*) [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
39: 0x100accc4c node::InternalCallbackScope::Close() [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
40: 0x100accfd0 node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
41: 0x100ae236c node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
42: 0x100b8ca60 node::fs::FSReqCallback::Reject(v8::Local<v8::Value>) [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
43: 0x100b8d2ec node::fs::FSReqAfterScope::Reject(uv_fs_s*) [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
44: 0x100b8d520 node::fs::AfterNoArgs(uv_fs_s*) [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
45: 0x100b83bb0 node::MakeLibuvRequestCallback<uv_fs_s, void (*)(uv_fs_s*)>::Wrapper(uv_fs_s*) [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
46: 0x1014b8070 uv__work_done [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
47: 0x1014bbac0 uv__async_io [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
48: 0x1014cdb98 uv__io_poll [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
49: 0x1014bc084 uv_run [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
50: 0x100acd6e0 node::SpinEventLoop(node::Environment*) [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
51: 0x100bc4850 node::NodeMainInstance::Run() [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
52: 0x100b546a4 node::LoadSnapshotDataAndRun(node::SnapshotData const**, node::InitializationResult const*) [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
53: 0x100b5495c node::Start(int, char**) [/Users/expo/.nvm/versions/node/v18.18.0/bin/node]
54: 0x1956020e0 start [/usr/lib/dyld]
yarn install exited with signal: SIGABRT

**Comment by CAMOBAP** [comment]
@Ruchita-Missio thanks for report, have you tried `env NODE_OPTIONS="--max-old-space-size=4096" yarn install`?

**Comment by CAMOBAP** [comment]
@Ruchita-Missio, please let me know if the issue is still affects you
