### ISSUE TITLE
Webview fades on / off for passive sitekey

### ISSUE THREAD

**Issue by brdlyptrs** [hCaptcha/react-native-hcaptcha#7]
### What
Allow the ability to hide the webview completely when using a passive sitekey.

### Why
Currently, using a passive sitekey requires calling `show()` and `execute()`, which also results in the webview fading on and then off once a response token is generated.

**Comment by e271828-** [comment]
How to stop this:

index.js:

1.

```
<Modal
...
                animationInTiming={1}
                animationOutTiming={1}
                backdropOpacity={0}
```

2.

```
const styles = ...
    modal: { margin: 0, display: 'none' },
```
