### ISSUE TITLE
Dependency versions issue

### ISSUE THREAD

**Issue by MamoshiSE** [hCaptcha/react-native-hcaptcha#9]
I am having issues with getting hcaptcha to work with the dependency packages. If I downgrade react-native-webview to 9.0.1 then I have to downgrade react verison, react native verison and other packages that break.

[stderr] npm ERR! Found: react-native-webview@11.17.2
[stderr] npm ERR! node_modules/react-native-webview
[stderr] npm ERR!   react-native-webview@"11.17.2" from the root project
[stderr] npm ERR! 
[stderr] npm ERR! Could not resolve dependency:
[stderr] npm ERR! peer react-native-webview@"^9.0.1" from @hcaptcha/react-native-hcaptcha@1.3.4
[stderr] npm ERR! node_modules/@hcaptcha/react-native-hcaptcha
[stderr] npm ERR!   @hcaptcha/react-native-hcaptcha@"^1.3.4" from the root project

My package json:
    "@expo/vector-icons": "^12.0.5",
    "@hcaptcha/react-native-hcaptcha": "^1.3.4",
    "@react-native-async-storage/async-storage": "~1.15.0",
    "@react-native-community/clipboard": "^1.5.1",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-firebase/app": "^14.5.0",
    "@react-navigation/drawer": "^5.12.5",
    "@react-navigation/material-top-tabs": "^5.3.15",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.5",
    "axios": "^0.26.0",
    "expo": "~44.0.0",
    "expo-app-loading": "^1.3.0",
    "expo-auth-session": "~3.5.0",
    "expo-dev-client": "^0.8.4",
    "expo-linear-gradient": "~11.0.3",
    "expo-localization": "~12.0.0",
    "expo-notifications": "~0.14.0",
    "expo-random": "~12.1.1",
    "expo-splash-screen": "~0.14.1",
    "expo-status-bar": "~1.2.0",
    "expo-updates": "^0.11.6",
    "formik": "^2.2.9",
    "i18n-js": "^3.8.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-app-intro-slider": "^4.0.4",
    "react-native-applovin-max": "^2.5.2",
    "react-native-collapsible": "^1.6.0",
    "react-native-confirmation-code-input": "^1.0.4",
    "react-native-dotenv": "^3.3.1",
    "react-native-elements": "^3.4.2",
    "react-native-fabric": "^0.5.2",
    "react-native-gesture-handler": "~2.1.0",
    "react-native-modal": "^11.5.4",
    "react-native-pager-view": "5.4.9",
    "react-native-reanimated": "^2.3.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.10.1",
    "react-native-tab-view": "^3.1.1",
    "react-native-vector-icons": "^9.1.0",
    "react-native-web": "0.17.1",
    "react-native-webview": "^11.0.0",
    "styled-components": "^5.3.3"

**Comment by e271828-** [comment]
@CAMOBAP please take a look.
